### ISSUE TITLE
Compose language service doesn't recognize `restart` option

### ISSUE THREAD

**Issue by DoctorKrolic** [microsoft/compose-language-service#133]
Example compose file:
```yml
version: '3.4'

services:
  test:
    restart: always
...
```
1) Howering over `restart` doesn't yield any results
2) If you remove `always` and try to invoke completions there, no results are shown, even though `restart` in docker compose has a finite set of well-known values: `no`, `always`, `on-failure`, `unless-stopped`
