### ISSUE TITLE
Map keys must be unique (DUPLICATE_KEY) on anchors

### ISSUE THREAD

**Issue by Zayon** [microsoft/compose-language-service#78]
The following yaml is a valid `docker-compose.yaml` declaration but vscode shows a "Map keys must be unique (DUPLICATE_KEY)" error on the `<<: *bar` line.

```yaml
version: 3.8

x-foo: &foo
  FOO: FOO

x-bar: &bar
  BAR: BAR

services:
  foo-bar:
    image: my-image
    environment:
      <<: *foo
      <<: *bar
```

Disabling the docker extension `ms-azuretools.vscode-docker` make the error disappear.

This issue is fixed in the YAML parser, see https://github.com/eemeli/yaml/issues/21
