### ISSUE TITLE
BAD_INDENT false positive if alias is used as mapping key in Docker Compose file

### ISSUE THREAD

**Issue by i-ky** [microsoft/compose-language-service#81]
When [alias](https://yaml.org/spec/1.2.2/#alias-nodes) is used as a key in `services:` mapping, e.g.
```yaml
version: "3.8"

x-service:
- &foo_service foo

services:
  *foo_service:
    image: alpine

  bar:
    image: busybox
    depends_on:
    - *foo_service
```
...extension reports _Problems_:
```json
[{
	"resource": "/C:/Users/i-ky/docker-compose.yml",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": "BAD_INDENT",
	"severity": 8,
	"message": "All mapping items must start at the same column",
	"startLineNumber": 8,
	"startColumn": 1,
	"endLineNumber": 8,
	"endColumn": 2
},{
	"resource": "/C:/Users/i-ky/docker-compose.yml",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": "BAD_INDENT",
	"severity": 8,
	"message": "All mapping items must start at the same column",
	"startLineNumber": 9,
	"startColumn": 1,
	"endLineNumber": 9,
	"endColumn": 2
}]
```
The config file is actually fine and no diagnostics should be emitted:
```
PS C:\Users\i-ky> docker-compose config
services:
  bar:
    depends_on:
      foo:
        condition: service_started
    image: busybox
  foo:
    image: alpine
version: '3.8'
```
Extension version: 1.19.0
VS Code version: 1.63.2
